name: Node.js CI with Docker Build

on:
  push:
    branches: [ "main" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Lint check (Syntax Check)
        run: node --check index.js

      - name: Build Docker Image
        run: |
          docker build -t electricity-api:${{ github.sha }} .
          echo "Build successful"